"""
api/model_index.py
------------------
Exact lexical matching of valve model codes mentioned in a user question.

Embeddings place "ITALICA 353" and "ITALICA 310" almost on top of each other, so
semantic search alone answers a question about one model with the other model's
data — or, when the wrong-model chunks crowd out the right ones, claims to have
no information at all. This module recovers the specific datasheet by name so
retrieval can pull it directly.

The registry is generated by ingest/build_model_registry.py. If it is missing,
every function here degrades to "no model detected" and retrieval falls back to
pure semantic search.
"""

from __future__ import annotations

import json
import logging
import re
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

REGISTRY_PATH = Path(__file__).resolve().parent / "model_registry.json"

# A Pinecone $in filter with too many values slows the query and dilutes the
# result set, so family-level matches (e.g. bare "XLC") are capped.
MAX_FILES_PER_QUERY = 8

_registry: Optional[dict] = None


def _load_registry() -> dict:
    """Load and cache the registry; return empty structure when absent."""
    global _registry
    if _registry is None:
        try:
            _registry = json.loads(REGISTRY_PATH.read_text(encoding="utf-8"))
        except FileNotFoundError:
            logger.warning(
                "model_index: %s not found — model-code matching disabled. "
                "Run: python -m ingest.build_model_registry",
                REGISTRY_PATH.name,
            )
            _registry = {"models": {}, "families": {}, "priority_docs": []}
        except (json.JSONDecodeError, OSError) as exc:
            logger.warning("model_index: could not read registry (%s)", exc)
            _registry = {"models": {}, "families": {}, "priority_docs": []}
    return _registry


def normalize_sequence(text: str) -> list[str]:
    """
    Tokenise free text the same way the registry keys were built, in order.

    Letter/digit runs are separated so 'Italica353' and 'ITALICA 353' produce
    identical tokens.
    """
    # Dotted acronyms first: the tank CSA sells as "A.V.A.S.T." is the file
    # AVAST.pdf, and splitting on the dots produced single letters that matched
    # nothing — the bot refused a product it documents. Only runs of dotted
    # single letters are collapsed; ordinary sentence punctuation is untouched.
    text = re.sub(
        r"\b(?:[A-Za-z]\.){2,}[A-Za-z]\.?",
        lambda m: m.group(0).replace(".", ""),
        text,
    )
    # Misure in pollici con frazione: CSA le scrive "1 1/4" e le codifica nel
    # nome file come 114 (ATHENA_114.pdf). Tokenizzate alla lettera davano
    # 1, 1, 4 — nessuna chiave del registry le raggiungeva — e una domanda
    # sulla ATHENA 1"-1 1/4" veniva risolta sulla ATHENA liscia, rispondendo
    # con la portata di un altro modello.
    text = re.sub(r"(\d)\s+(\d)\s*/\s*(\d)", r"\1\2\3", text)
    cleaned = re.sub(r"[^A-Za-z0-9]+", " ", text)
    cleaned = re.sub(r"(?<=[A-Za-z])(?=\d)", " ", cleaned)
    cleaned = re.sub(r"(?<=\d)(?=[A-Za-z])", " ", cleaned)
    return [t.lower() for t in cleaned.split() if t]


def normalize_tokens(text: str) -> set[str]:
    """Unordered form of `normalize_sequence`, kept for callers that want a set."""
    return set(normalize_sequence(text))


# ---------------------------------------------------------------------------
# Misspelling tolerance
# ---------------------------------------------------------------------------
# Users type product names by ear: "atena" for ATHENA, "italika" for ITALICA,
# "ciclops" for CYCLOPS. Exact token matching answered every one of those with
# "I have no information on this product" — while attaching, at one point, an
# unrelated product's drawing. A query token that matches nothing is therefore
# aligned to a *family name* when, and only when, the correction is safe:
#   - the token is ≥5 letters (at 4, "solo" — the everyday Italian word — is
#     one edit from the EOLO family, and every stray adverb became a valve);
#   - it starts with the same letter as the candidate (typos rarely hit the
#     first letter, and this kills "largo" → ARGO);
#   - exactly one family is within one edit (an ambiguous typo names nothing).
# Targets are family names only: parts of document names like "sizing" or
# "engineering" gain nothing from fuzzy matching and widen the blast radius.


def _one_edit_apart(a: str, b: str) -> bool:
    """True when *a* and *b* differ by one substitution, insertion or deletion."""
    if a == b:
        return False
    la, lb = len(a), len(b)
    if abs(la - lb) > 1:
        return False
    if la == lb:
        return sum(1 for x, y in zip(a, b) if x != y) == 1
    if la > lb:
        a, b, la, lb = b, a, lb, la
    # b is one char longer: skip exactly one char of b
    i = 0
    while i < la and a[i] == b[i]:
        i += 1
    return a[i:] == b[i + 1:]


def _fuzzy_align(sequence: list[str]) -> list[str]:
    """Map misspelled product names in *sequence* onto their family name."""
    families = _load_registry().get("families", {})
    targets = [f for f in families if f.isalpha() and len(f) >= 4]
    known = set(targets)

    aligned: list[str] = []
    for token in sequence:
        if token in known or not token.isalpha() or len(token) < 5:
            aligned.append(token)
            continue
        close = [
            t for t in targets
            if t[0] == token[0] and _one_edit_apart(token, t)
        ]
        aligned.append(close[0] if len(close) == 1 else token)
    return aligned


# Tokens that may sit inside a spoken model code without being part of the
# registry key. CSA writes dual-series names — "XLC 365/465-MCP" is the sheet
# XLC_365_MCP.pdf — and puts the family denominator in titles the filenames
# drop: the sheet SATURNO_RFP.pdf titles itself "SATURNO 3F - RFP". Matching
# strictly contiguously, both spoken forms named no model and the bot refused
# values its own sheet documents. Only these may be skipped, and only *between*
# matched tokens: a word like "dn" still breaks the run, which is what keeps
# "XLC 400 DN 300" from reading as an XLC 300.
# Numeri inclusi: una misura in pollici puo' stare dentro il nome parlato di un
# modello — "ATHENA 1\" - 1 1/4\"" e' la ATHENA 114 — e il primo 1 spezzava la
# sequenza. Le taglie continuano a fermarla tramite la parola che le introduce
# ("DN", "PN"), che non e' saltabile: e' quello che impedisce a "XLC 400 DN 300"
# di leggersi come una XLC 300.
_SKIPPABLE_INFIX = re.compile(r"^(?:3f?|f|\d{1,4})$")
_MAX_SKIPPED = 2


def _names_model(sequence: list[str], key_tokens: list[str]) -> bool:
    """
    True when *key_tokens* appear in order in *sequence*, consecutively except
    for up to _MAX_SKIPPED skippable infix tokens (see _SKIPPABLE_INFIX).

    Matching an unordered bag of tokens read a size as a model number: in
    "Quanto pesa la valvola XLC 400 DN 300?" both "xlc" and "300" are present,
    so the key 'xlc 300' matched and the question about an XLC 400 was answered
    from an XLC 300 datasheet. A model code is written as adjacent words, so
    adjacency — with the narrow skip list above — is what identifies it.
    """
    if not key_tokens or len(key_tokens) > len(sequence):
        return False
    first = key_tokens[0]
    for start in range(len(sequence) - len(key_tokens) + 1):
        if sequence[start] != first:
            continue
        pos, skipped, matched = start + 1, 0, 1
        while matched < len(key_tokens) and pos < len(sequence):
            if sequence[pos] == key_tokens[matched]:
                matched += 1
                pos += 1
            elif skipped < _MAX_SKIPPED and _SKIPPABLE_INFIX.match(sequence[pos]):
                skipped += 1
                pos += 1
            else:
                break
        if matched == len(key_tokens):
            return True
    return False


def find_model_sources(query: str) -> list[str]:
    """
    Return datasheet filenames for the most specific model the query names.

    Specificity wins: a question naming "XLC 310 DC" resolves to that datasheet
    rather than to every XLC document. When only a family is named ("what XLC
    valves do you have?") the family's documents are returned, preferring the
    up-to-date engineering set.
    """
    if names_excluded_model(query):
        return []
    registry = _load_registry()
    models: dict[str, list[str]] = registry.get("models", {})
    families: dict[str, list[str]] = registry.get("families", {})
    priority: set[str] = set(registry.get("priority_docs", []))

    sequence = _fuzzy_align(normalize_sequence(query))
    tokens = set(sequence)
    if not sequence:
        return []

    # Model-level match: the key's tokens must appear consecutively.
    best_specificity = 0
    matched: set[str] = set()
    for key, files in models.items():
        key_tokens = key.split()
        if not _names_model(sequence, key_tokens):
            continue
        specificity = len(key_tokens)
        if specificity > best_specificity:
            best_specificity = specificity
            matched = set(files)
        elif specificity == best_specificity:
            matched.update(files)

    if matched:
        return _cap(matched, priority)

    # Family-level fallback: the question names a product line but no model.
    family_files: set[str] = set()
    for family, files in families.items():
        if family in tokens:
            family_files.update(files)

    if family_files:
        return _cap(family_files, priority)

    return []


# Datasheets pulled in for an application question. Higher than the model cap:
# "what do you recommend for irrigation?" should be answered from a spread of
# products, and 32 datasheets name irrigation.
MAX_APPLICATION_FILES = 14

# Query wording -> the registry applications it should pull in. Matched against
# the English rendering of the question that retrieval already builds, so only
# English phrasings are needed here.
#
# Each question maps to the one application it names, and retrieval pulls only
# datasheets documented for exactly that.
#
# An earlier version let a drinking-water question also pull the water-supply
# datasheets, on the reasoning that for a waterworks manufacturer they are the
# same job. It gave breadth but put products into the context that the model then
# listed under a "documented for drinking water" heading although their own
# datasheets never say so — and for a valve, suitability and potable-water
# approval are different claims. Three attempts at wording the prompt around it
# did not hold, so the borrowing was removed instead: with the applications now
# unified across the language editions of a document, an exact match already
# yields eight datasheets for drinking water.
_APPLICATION_TERMS: dict[tuple[str, ...], tuple[str, ...]] = {
    ("irrigation", "irrigate", "sprinkler", "farming", "agricultur"): ("irrigation",),
    ("sewage", "waste water", "wastewater", "sewer"): ("sewage",),
    ("drinking water", "potable", "tap water"): ("drinking water",),
    ("sea water", "seawater", "desalination", "marine"): ("sea water",),
    ("fire fighting", "firefighting", "hydrant", "fire protection"): ("fire fighting",),
    ("pumping station", "pump station"): ("pumping station",),
    # "industrial" alone missed "industry", the commonest phrasing, and the
    # question about industry returned no product at all.
    ("industr", "process plant", "refiner", "petrochemical", "manufacturing"):
        ("industrial",),
    ("water supply", "distribution network", "water main", "aqueduct", "waterworks"):
        ("water supply network",),
    ("mining", "mine ", "quarry"): ("mining",),
    ("deep well", "borehole"): ("deep well",),
    # Non-English wordings, for when translate_to_english fails quietly.
    ("dissalazione", "desalinizzazione", "dessalement", "desalación", "desalacion"):
        ("sea water",),
    ("miniera", "minerario", "minerarios"): ("mining",),
}


def find_application_sources(query: str) -> list[str]:
    """
    Return datasheets documented for the application the question names.

    Application questions ("what do you recommend for irrigation?") cannot be
    served by passage similarity alone: the answer is a *set of products*, and
    the two best-matching chunks come from one or two of them. Pulling the
    application's datasheets in as candidates gives the reranker a spread of
    products to choose between.

    *query* should be the English rendering of the question, since the registry
    was built from the English datasheets.
    """
    registry = _load_registry()
    by_application: dict[str, list[str]] = registry.get("applications", {})
    if not by_application:
        return []

    lowered = query.lower()
    matched: set[str] = set()
    for terms, keys in _APPLICATION_TERMS.items():
        if any(term in lowered for term in terms):
            for key in keys:
                matched.update(by_application.get(key, []))

    priority = set(registry.get("priority_docs", []))
    preferred = sorted(f for f in matched if f in priority)
    rest = sorted(f for f in matched if f not in priority)
    return (preferred + rest)[:MAX_APPLICATION_FILES]


def _is_own_file(key: str, file_name: str) -> bool:
    """
    True when a one-token code is a model name rather than a family name.

    "VRCA" and "ATHENA" are complete model codes that happen to be one word,
    and requiring two tokens left those models without an exact match at all.
    But "XLC" is a family of fifty documents whose base file is the generic
    XLC_ENG.pdf, and accepting it as an exact code answered "quanto pesa la
    XLC 600" from that file. The base document of a real one-word model is
    named after the model itself — ARGO.pdf, SCF.pdf — while a family's is not.
    """
    return normalize_sequence(Path(file_name).stem) == key.split()


def names_excluded_model(query: str) -> bool:
    """
    True quando la domanda nomina un modello la cui scheda e' stata tolta
    dall'indice di proposito.

    Senza questo controllo la domanda ricade sulla chiave piu' corta e riceve
    la scheda di un altro prodotto: tolta APOLLO_RPC_SMART.pdf, "Apollo RPC
    SMART" risolveva APOLLO_RPC.pdf — cioe' l'idrante non-SMART — e il
    contesto lo etichettava "questa e' la scheda del modello chiesto".
    Meglio nessuna scheda che la scheda sbagliata: il prodotto resta
    descrivibile dalle pagine del sito.
    """
    esclusi = _load_registry().get("excluded", [])
    if not esclusi:
        return False
    sequence = _fuzzy_align(normalize_sequence(query))
    return any(_names_model(sequence, k.split()) for k in esclusi)


def find_exact_model_source(query: str) -> Optional[str]:
    """
    Return the datasheet whose own model code the query names, if any.

    The keys in `models` are prefixes shared across a family — 'fox 3 f' resolves
    to all nine FOX 3F documents so that a range question reaches them. That left
    no way to tell that FOX_3F.pdf *is* the FOX 3F while the others are variants
    of it, and a question about the base model was answered from a variant: the
    FOX 3F came back at 64 bar, the rating of the carbon-steel FOX 3F-HP, while
    the base valve is ductile iron PN 40.

    `canonical` maps each document's complete code to its file, so the most
    specific code fully named in the question wins: "pressure of the FOX 3F"
    resolves to FOX_3F.pdf, "pressure of the FOX 3F HP" to FOX_3F_HP.pdf.

    Single-word codes count too: "VRCA" and "ATHENA" are complete model codes,
    and requiring two tokens meant those models never got an exact match — no
    datasheet banner, no variant labels on the other products in context, and
    the bot refused the VRCA's weight with the row in front of it because an
    unlabelled catalogue page of another family sat alongside. The guard that
    matters is kept in a sharper form: when two *different* files match with
    equally specific codes — a comparison question, "differenza tra ATHENA e
    GEMINA" — neither is THE model asked about, and no exact match is returned.
    """
    if names_excluded_model(query):
        return None
    registry = _load_registry()
    canonical: dict[str, str] = registry.get("canonical", {})
    if not canonical:
        return None

    sequence = _fuzzy_align(normalize_sequence(query))
    matched: list[str] = [
        key for key in canonical
        if _names_model(sequence, key.split())
        and (len(key.split()) > 1 or _is_own_file(key, canonical[key]))
    ]
    if not matched:
        return None
    longest = max(len(key.split()) for key in matched)
    winners = {
        canonical[key] for key in matched if len(key.split()) == longest
    }
    if len(winners) != 1:
        return None
    return next(iter(winners))


def find_family(query: str) -> Optional[str]:
    """
    The product family the query names, if any — misspellings included.

    Some families publish dimensions once per series in the general catalogue
    only: the ITALICA datasheets carry no dimension table at all, the catalogue
    page "Italica 300 - Dimensioni e pesi" does. Retrieval uses this to fetch
    the family's catalogue pages, which nothing else links to the model name.
    """
    families = _load_registry().get("families", {})
    for token in _fuzzy_align(normalize_sequence(query)):
        if token in families:
            return token
    return None


# The XLC 500/600 ranges publish their sizes and weights in their own sizing
# document, not in the engineering manual that covers the 300 and 400. Which
# document carries a range's tables is a fact about CSA's documentation, not
# something the file names reveal.
_XLC_500_DOCS = ("XLC_500_SIZING.pdf", "XLC_500_INTRO.pdf")


def _all_files(registry: dict) -> set[str]:
    """Every datasheet the registry knows, from the family index."""
    return {f for files in registry.get("families", {}).values() for f in files}


def find_series_documents(query: str) -> list[str]:
    """
    Return the range-level documents that cover the model the query names.

    Individual XLC datasheets carry no dimensions: not one of XLC_310.pdf,
    XLC_330.pdf and their siblings has a weight table. Sizes and weights are
    published once per range in the XLC engineering document — the XLC 400
    (full bore) and XLC 300 (reduced bore) tables — and a model like the
    XLC 330/430 takes the 300-series figures for its 330 and the 400-series
    figures for its 430. Asked what an XLC 330/430 weighs, the bot read only
    that model's own datasheet and answered that the weight was not documented.
    """
    if names_excluded_model(query):
        return []
    registry = _load_registry()
    priority: list[str] = registry.get("priority_docs", [])
    if not priority:
        return []

    sequence = _fuzzy_align(normalize_sequence(query))
    families = registry.get("families", {})

    # The XLC 500 and 600 ranges are documented apart from the engineering
    # manual, which only covers the 300 and 400. Without this the 5xx/6xx
    # sizing pages were never fetched: "quanto pesa la XLC 600 DN 100" was
    # answered with the XLC 300's 34 kg, and the 500's DN range was refused.
    for token, next_token in zip(sequence, sequence[1:] + [""]):
        if token == "xlc" and next_token[:1] in ("5", "6"):
            covering = [f for f in _XLC_500_DOCS if f in _all_files(registry)]
            if covering:
                return covering

    for index, token in enumerate(sequence):
        if token not in families:
            continue
        # The family is named, and the range documents are its priority set.
        covering = [f for f in priority if token in normalize_tokens(f)]
        if covering:
            return covering
    return []


def sources_mentioned(text: str) -> set[str]:
    """
    Return every datasheet whose model code appears in *text*.

    Used to work out which products an answer already covered, so a follow-up
    like "e basta?" can look past them. Unlike find_model_sources this does not
    keep only the most specific match: the point here is completeness, since a
    single answer routinely names four or five products.
    """
    registry = _load_registry()
    sequence = normalize_sequence(text)
    if not sequence:
        return set()

    found: set[str] = set()
    for key, files in registry.get("models", {}).items():
        if _names_model(sequence, key.split()):
            found.update(files)
    return found


def is_catalogue(source_file: str) -> bool:
    """
    True when *source_file* is a general catalogue, not a product datasheet.

    The context labels every other datasheet as "DIFFERENT PRODUCT — never take
    its figures" when the named model's own sheet is present. Applied to the
    catalogue, that instruction forbade the only table in the corpus holding the
    ITALICA dimensions — the family publishes them in the catalogue alone — and
    the bot refused figures it was looking at.
    """
    if not source_file:
        return False
    catalogues = _load_registry().get("catalogues", [])
    if source_file in catalogues:
        return True
    return "catalog" in source_file.lower() or "catalogo" in source_file.lower()


def applications_for(source_file: str) -> list[str]:
    """
    Return the applications a datasheet documents.

    Surfaced in the prompt context because a retrieved chunk often covers
    materials or the operating principle and never repeats what the valve is
    for — so the model saw five products documented for irrigation and named
    only the one whose chunk happened to contain the word.
    """
    if not source_file:
        return []
    registry = _load_registry()
    return sorted(
        name
        for name, files in registry.get("applications", {}).items()
        if source_file in files
    )


def features_for(source_file: str) -> list[str]:
    """
    Le caratteristiche costruttive che una scheda documenta.

    Dichiarate nel contesto come le applicazioni, e per lo stesso motivo: le
    schede sono in inglese ("cover with threaded outlet for air conveyance") e
    a "avete valvole convogliate?" il modello non collegava, pur avendo davanti
    le quattro schede giuste. Recuperarle non bastava: andava detto.
    """
    if not source_file:
        return []
    registry = _load_registry()
    return sorted(
        name
        for name, files in registry.get("features", {}).items()
        if source_file in files
    )


def _cap(files: set[str], priority: set[str]) -> list[str]:
    """Trim to MAX_FILES_PER_QUERY, keeping priority documents first."""
    preferred = sorted(f for f in files if f in priority)
    rest = sorted(f for f in files if f not in priority)
    return (preferred + rest)[:MAX_FILES_PER_QUERY]


# ---------------------------------------------------------------------------
# Sections inside multi-product datasheets
# ---------------------------------------------------------------------------
# Some files document more than one product: APOLLO_RPC.pdf opens with the
# Apollo RP and continues with the Apollo RPC, SCS_AS.pdf appends the GOLIA SUB
# kit, XLC_PILOTS.pdf holds eight distinct pilots. The "this is the datasheet of
# exactly the model asked about" banner is per file, so it endorsed the other
# product's pages too: the Apollo RPC's quota A came back as the RP's 682 mm and
# the SCS-AS's weight as the SUB kit's 7,0-88,3 kg.
#
# Generated by ingest/build_section_map.py: {file: {page: model documented}}.
SECTION_MAP_PATH = Path(__file__).resolve().parent / "section_map.json"

try:
    _SECTION_MAP: dict[str, dict[str, str]] = json.loads(
        SECTION_MAP_PATH.read_text(encoding="utf-8")
    )
except (FileNotFoundError, json.JSONDecodeError):
    _SECTION_MAP = {}


def section_of(source_file: str, page) -> Optional[str]:
    """The product a given page of a multi-product datasheet documents."""
    pages = _SECTION_MAP.get(source_file or "")
    if not pages or page is None:
        return None
    return pages.get(str(page))


def find_sections(query: str) -> dict[str, str]:
    """
    {file: section} for every multi-product file whose section the query names.

    The most specific section wins within each file, so "Apollo RPC" resolves to
    that section and not to the "Apollo RP" one that shares its first token.
    """
    # Anche da qui: la domanda sull'APOLLO RPC SMART nominava la sezione
    # "Apollo RPC" e si riportava in contesto la scheda dell'idrante
    # non-SMART, etichettata come quella del modello chiesto.
    if names_excluded_model(query):
        return {}
    sequence = _fuzzy_align(normalize_sequence(query))
    if not sequence:
        return {}

    found: dict[str, str] = {}
    for file_name, pages in _SECTION_MAP.items():
        best = ""
        for section in dict.fromkeys(pages.values()):
            tokens = normalize_sequence(section)
            if tokens and _names_model(sequence, tokens):
                if len(tokens) > len(normalize_sequence(best)) if best else True:
                    best = section
        if best:
            found[file_name] = best
    return found


def files_with_sections(query: str) -> list[str]:
    """
    Datasheets reachable only through a section name.

    The registry is built from file names, so a product documented inside
    another product's file is invisible to it: asked for the CSFL flow
    regulator's dimensions — a section of XLC_PILOTS.pdf — retrieval never
    fetched the file and the answer was "I have no information".
    """
    return sorted(find_sections(query))


# The general catalogue devotes separate pages to each series of a family: page
# 298 is the XLC 500, 254 the XLC 400, 423 the Italica 300. They are all "XLC"
# or "ITALICA" pages in the metadata, so treating them alike told the model the
# XLC 500's table answered a question about an XLC 330 — its DN 80 came back as
# 20 kg instead of 24. The series is rarely in the heading (usually a chart) but
# is named in the page body; ingest/build_section_map.py extracts it per page.
PAGE_SERIES_PATH = Path(__file__).resolve().parent / "page_series.json"

try:
    _PAGE_SERIES: dict[str, dict[str, list[str]]] = json.loads(
        PAGE_SERIES_PATH.read_text(encoding="utf-8")
    )
except (FileNotFoundError, json.JSONDecodeError):
    _PAGE_SERIES = {}


def series_on_page(source_file: str, page) -> set[str]:
    """Series designations a given page documents ({'xlc 500'})."""
    pages = _PAGE_SERIES.get(source_file or "")
    if not pages or page is None:
        return set()
    return set(pages.get(str(page), []))


# ---------------------------------------------------------------------------
# Pagine prodotto del sito, per categoria
# ---------------------------------------------------------------------------
# L'elenco che il bot produce a "quali idranti fate?" si costruisce dall'indice
# delle schede tecniche. Un prodotto che il sito pubblica ma nessuna scheda
# indicizzata documenta non compariva: l'APOLLO RPC SMART rispondeva benissimo
# quando lo si nominava — la sua pagina e' nell'indice — ma spariva dagli
# elenchi. Generato da ingest/build_site_products.py.
SITE_PRODUCTS_PATH = Path(__file__).resolve().parent / "site_products.json"

try:
    _SITE_PRODUCTS: dict[str, dict] = json.loads(
        SITE_PRODUCTS_PATH.read_text(encoding="utf-8")
    )
except (FileNotFoundError, json.JSONDecodeError):
    _SITE_PRODUCTS = {}


def find_category_products(query: str) -> list[str]:
    """
    URL delle pagine prodotto della categoria che la domanda nomina.

    Gli slug sono registrati nelle quattro lingue, altrimenti "which hydrants
    do you make?" non incontrerebbe mai la parola italiana "idranti". Se la
    domanda nomina un modello preciso non si restituisce nulla: l'elenco di
    categoria servirebbe solo a diluire il contesto.
    """
    if not _SITE_PRODUCTS or find_exact_model_source(query):
        return []

    parole = set(normalize_sequence(query))
    urls: list[str] = []
    for voce in _SITE_PRODUCTS.values():
        for slug in voce.get("slug_lingue", []):
            token = normalize_sequence(slug)
            if token and _nomina_categoria(token, parole):
                urls += [pr["url"] for pr in voce.get("prodotti", [])]
                break
    return sorted(set(urls))


# Teste di slug troppo generiche per identificare da sole una categoria: chi
# scrive "valvole" sta quasi sempre parlando d'altro, e prendere l'intera
# categoria diluirebbe il contesto di quindici pagine.
_TESTE_GENERICHE = {
    "valvole", "valvola", "valves", "valve", "valvulas", "valvula",
    "vannes", "vanne", "prodotti", "products", "accessori", "accessories",
}


def _nomina_categoria(token: list[str], parole: set[str]) -> bool:
    """
    True quando la domanda nomina la categoria di quello slug.

    Pretendere tutte le parole dello slug funziona in italiano, dove sono
    slug di una parola ("idranti", "sfiati"), ma non in inglese: la categoria
    e' "pillar-fire-hydrants" e nessuno scrive "which pillar fire hydrants do
    you make". Basta allora la parola-chiave finale, purche' non sia una di
    quelle che da sole non dicono nulla.
    """
    if set(token) <= parole:
        return True
    testa = token[-1]
    return len(testa) >= 5 and testa not in _TESTE_GENERICHE and testa in parole


# ---------------------------------------------------------------------------
# Caratteristiche costruttive
# ---------------------------------------------------------------------------
# "Avete valvole convogliate?" riceveva un rifiuto mentre quattro schede lo
# sono — il concetto e' una caratteristica, e l'indice esisteva solo per le
# applicazioni. Le caratteristiche stanno nel registro, dedotte dal suffisso
# del codice (i "modelli C"), e la domanda le nomina in quattro lingue.
FEATURE_QUERY_PATTERNS: dict[str, str] = {
    "conveyed air discharge": (
        r"convogli|conveyed|air conveyance|scarico convogliato|scarico canalizzato"
        r"|achemin|canalizad"
    ),
    "anti-shock": r"anti[- ]?shock|anti[- ]?colpo d|non[- ]?slam|anti[- ]?slam|antichoc",
    "anti-surge": r"anti[- ]?surge|anti[- ]?ariete|colpo d.ariete|anti[- ]?b[eé]lier|golpe de ariete",
    "remote monitoring": (
        r"controllo remoto|telecontroll|remote (?:control|monitoring)|monitoraggio remoto"
    ),
}

_FEATURE_RX = {k: re.compile(v, re.I) for k, v in FEATURE_QUERY_PATTERNS.items()}


def find_feature_sources(query: str) -> list[str]:
    """
    Le schede che hanno la caratteristica costruttiva nominata dalla domanda.

    Non si cerca la parola nella prosa: "convogliamento" compare in trenta
    schede, quasi tutte perche' lo CITANO (un rimando, un kit accodato). Le
    otto che lo sono davvero si riconoscono dal codice, ed e' anche quello che
    intende il cliente quando dice "i modelli C".
    """
    features = _load_registry().get("features", {})
    if not features:
        return []
    trovate: set[str] = set()
    for nome, rx in _FEATURE_RX.items():
        if rx.search(query):
            trovate.update(features.get(nome, []))
    return sorted(trovate)[:MAX_FILES_PER_QUERY]


# ---------------------------------------------------------------------------
# Programmi di calcolo
# ---------------------------------------------------------------------------
# Le pagine dei programmi di dimensionamento stanno quasi tutte dietro il login,
# quindi il crawler ne indicizza un puntatore che non dice la cosa che serve:
# quali valvole quel programma dimensiona. L'indice generato da
# ingest/build_sizing_programs.py lo dice, e queste funzioni lo interrogano.
#
# Il caso d'origine: "c'e' un calcolatore per la valvola AUGUSTA?" riceveva un
# rifiuto seguito dal link al calcolatore XLC — il programma di un'altra
# famiglia, senza dire che era di un'altra famiglia.
SIZING_PATH = Path(__file__).resolve().parent / "sizing_programs.json"

_sizing: Optional[dict] = None


def _load_sizing() -> dict:
    """Carica e tiene in cache l'indice dei programmi; vuoto se manca."""
    global _sizing
    if _sizing is None:
        try:
            _sizing = json.loads(SIZING_PATH.read_text(encoding="utf-8"))
        except FileNotFoundError:
            logger.warning(
                "model_index: %s assente — indice dei programmi di calcolo "
                "disattivato. Esegui: python -m ingest.build_sizing_programs",
                SIZING_PATH.name,
            )
            _sizing = {"programmi": [], "indice_sezione": []}
        except (json.JSONDecodeError, OSError) as exc:
            logger.warning("model_index: indice dei programmi illeggibile (%s)", exc)
            _sizing = {"programmi": [], "indice_sezione": []}
    return _sizing


# "dimensionare" e "calcolare" nelle quattro lingue, piu' i nomi dei programmi.
# Volutamente stretto: "quanto pesa" non e' una domanda di dimensionamento, e
# far entrare le pagine dei programmi in ogni domanda tecnica ruberebbe uno dei
# sei slot alla scheda che porta la cifra.
_SIZING_QUERY = re.compile(
    r"\bcalcolator\w*|\bcalculator\w*|\bcalculateur\w*|\bcalculador\w*"
    r"|\bprogramm\w*\b[^.?!]{0,20}\bcalcol\w*|\bprograma\w*\b[^.?!]{0,20}\bc[aá]lculo"
    r"|\bsizing\b|\bdimension(?:o|a|amo|ate|ano|are|ato|ata|ati|amento|ando)\b"
    r"|\bdimensionn\w*|\bdimensionamiento\b|\bdimensionar\w*"
    r"|\bhow\b[^?.!]{0,30}\bsize\b|\bcsa\s+(?:cvs|lvs|rvs|prs|avs)\b",
    re.I,
)


def query_about_sizing(query: str) -> bool:
    """True quando la domanda riguarda un programma di calcolo/dimensionamento."""
    return bool(_SIZING_QUERY.search(query))


def find_sizing_programs(query: str) -> dict:
    """
    I programmi di calcolo pertinenti alla domanda.

    Restituisce sempre l'elenco completo — a chi chiede "che programmi avete?"
    servono tutti, e a chi ne chiede uno che non esiste serve sapere quali
    esistono invece di sentirsi dire "non ho informazioni". `pertinenti` sono
    quelli che dimensionano una famiglia nominata nella domanda: separarli e'
    cio' che impedisce di offrire il calcolatore XLC a chi ha chiesto della
    AUGUSTA.
    """
    if not query_about_sizing(query):
        return {}
    programmi = _load_sizing().get("programmi", [])
    if not programmi:
        return {}

    parole = set(normalize_sequence(query))
    famiglie_chieste = {
        f.upper() for f in _load_registry().get("families", {}) if f.lower() in parole
    }
    def pertinente(programma: dict) -> bool:
        if famiglie_chieste & {f.upper() for f in programma.get("famiglie", [])}:
            return True
        # Chi scrive "come dimensiono una valvola a galleggiante?" non nomina
        # nessuna serie, ma sta chiedendo esattamente il programma LVS. Vale
        # solo quando nessuna famiglia e' nominata: se la domanda dice AUGUSTA,
        # comanda la famiglia, non il tipo.
        tipo = programma.get("parole_tipo")
        return bool(tipo) and not famiglie_chieste and bool(re.search(tipo, query, re.I))

    pertinenti = [p for p in programmi if pertinente(p)]
    return {
        "pertinenti": pertinenti,
        "tutti": programmi,
        "famiglie_chieste": sorted(famiglie_chieste),
        "indice_sezione": _load_sizing().get("indice_sezione", []),
    }
