"""
api/model_index.py
------------------
Exact lexical matching of valve model codes mentioned in a user question.

Embeddings place "ITALICA 353" and "ITALICA 310" almost on top of each other, so
semantic search alone answers a question about one model with the other model's
data — or, when the wrong-model chunks crowd out the right ones, claims to have
no information at all. This module recovers the specific datasheet by name so
retrieval can pull it directly.

The registry is generated by ingest/build_model_registry.py. If it is missing,
every function here degrades to "no model detected" and retrieval falls back to
pure semantic search.
"""

from __future__ import annotations

import json
import logging
import re
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

REGISTRY_PATH = Path(__file__).resolve().parent / "model_registry.json"

# A Pinecone $in filter with too many values slows the query and dilutes the
# result set, so family-level matches (e.g. bare "XLC") are capped.
MAX_FILES_PER_QUERY = 8

_registry: Optional[dict] = None


def _load_registry() -> dict:
    """Load and cache the registry; return empty structure when absent."""
    global _registry
    if _registry is None:
        try:
            _registry = json.loads(REGISTRY_PATH.read_text(encoding="utf-8"))
        except FileNotFoundError:
            logger.warning(
                "model_index: %s not found — model-code matching disabled. "
                "Run: python -m ingest.build_model_registry",
                REGISTRY_PATH.name,
            )
            _registry = {"models": {}, "families": {}, "priority_docs": []}
        except (json.JSONDecodeError, OSError) as exc:
            logger.warning("model_index: could not read registry (%s)", exc)
            _registry = {"models": {}, "families": {}, "priority_docs": []}
    return _registry


def normalize_sequence(text: str) -> list[str]:
    """
    Tokenise free text the same way the registry keys were built, in order.

    Letter/digit runs are separated so 'Italica353' and 'ITALICA 353' produce
    identical tokens.
    """
    cleaned = re.sub(r"[^A-Za-z0-9]+", " ", text)
    cleaned = re.sub(r"(?<=[A-Za-z])(?=\d)", " ", cleaned)
    cleaned = re.sub(r"(?<=\d)(?=[A-Za-z])", " ", cleaned)
    return [t.lower() for t in cleaned.split() if t]


def normalize_tokens(text: str) -> set[str]:
    """Unordered form of `normalize_sequence`, kept for callers that want a set."""
    return set(normalize_sequence(text))


# ---------------------------------------------------------------------------
# Misspelling tolerance
# ---------------------------------------------------------------------------
# Users type product names by ear: "atena" for ATHENA, "italika" for ITALICA,
# "ciclops" for CYCLOPS. Exact token matching answered every one of those with
# "I have no information on this product" — while attaching, at one point, an
# unrelated product's drawing. A query token that matches nothing is therefore
# aligned to a *family name* when, and only when, the correction is safe:
#   - the token is ≥5 letters (at 4, "solo" — the everyday Italian word — is
#     one edit from the EOLO family, and every stray adverb became a valve);
#   - it starts with the same letter as the candidate (typos rarely hit the
#     first letter, and this kills "largo" → ARGO);
#   - exactly one family is within one edit (an ambiguous typo names nothing).
# Targets are family names only: parts of document names like "sizing" or
# "engineering" gain nothing from fuzzy matching and widen the blast radius.


def _one_edit_apart(a: str, b: str) -> bool:
    """True when *a* and *b* differ by one substitution, insertion or deletion."""
    if a == b:
        return False
    la, lb = len(a), len(b)
    if abs(la - lb) > 1:
        return False
    if la == lb:
        return sum(1 for x, y in zip(a, b) if x != y) == 1
    if la > lb:
        a, b, la, lb = b, a, lb, la
    # b is one char longer: skip exactly one char of b
    i = 0
    while i < la and a[i] == b[i]:
        i += 1
    return a[i:] == b[i + 1:]


def _fuzzy_align(sequence: list[str]) -> list[str]:
    """Map misspelled product names in *sequence* onto their family name."""
    families = _load_registry().get("families", {})
    targets = [f for f in families if f.isalpha() and len(f) >= 4]
    known = set(targets)

    aligned: list[str] = []
    for token in sequence:
        if token in known or not token.isalpha() or len(token) < 5:
            aligned.append(token)
            continue
        close = [
            t for t in targets
            if t[0] == token[0] and _one_edit_apart(token, t)
        ]
        aligned.append(close[0] if len(close) == 1 else token)
    return aligned


def _names_model(sequence: list[str], key_tokens: list[str]) -> bool:
    """
    True when *key_tokens* appear consecutively in *sequence*.

    Matching an unordered bag of tokens read a size as a model number: in
    "Quanto pesa la valvola XLC 400 DN 300?" both "xlc" and "300" are present,
    so the key 'xlc 300' matched and the question about an XLC 400 was answered
    from an XLC 300 datasheet. A model code is written as adjacent words, so
    adjacency is what identifies it.
    """
    if not key_tokens or len(key_tokens) > len(sequence):
        return False
    first = key_tokens[0]
    for start in range(len(sequence) - len(key_tokens) + 1):
        if sequence[start] == first and sequence[start : start + len(key_tokens)] == key_tokens:
            return True
    return False


def find_model_sources(query: str) -> list[str]:
    """
    Return datasheet filenames for the most specific model the query names.

    Specificity wins: a question naming "XLC 310 DC" resolves to that datasheet
    rather than to every XLC document. When only a family is named ("what XLC
    valves do you have?") the family's documents are returned, preferring the
    up-to-date engineering set.
    """
    registry = _load_registry()
    models: dict[str, list[str]] = registry.get("models", {})
    families: dict[str, list[str]] = registry.get("families", {})
    priority: set[str] = set(registry.get("priority_docs", []))

    sequence = _fuzzy_align(normalize_sequence(query))
    tokens = set(sequence)
    if not sequence:
        return []

    # Model-level match: the key's tokens must appear consecutively.
    best_specificity = 0
    matched: set[str] = set()
    for key, files in models.items():
        key_tokens = key.split()
        if not _names_model(sequence, key_tokens):
            continue
        specificity = len(key_tokens)
        if specificity > best_specificity:
            best_specificity = specificity
            matched = set(files)
        elif specificity == best_specificity:
            matched.update(files)

    if matched:
        return _cap(matched, priority)

    # Family-level fallback: the question names a product line but no model.
    family_files: set[str] = set()
    for family, files in families.items():
        if family in tokens:
            family_files.update(files)

    if family_files:
        return _cap(family_files, priority)

    return []


# Datasheets pulled in for an application question. Higher than the model cap:
# "what do you recommend for irrigation?" should be answered from a spread of
# products, and 32 datasheets name irrigation.
MAX_APPLICATION_FILES = 14

# Query wording -> the registry applications it should pull in. Matched against
# the English rendering of the question that retrieval already builds, so only
# English phrasings are needed here.
#
# Each question maps to the one application it names, and retrieval pulls only
# datasheets documented for exactly that.
#
# An earlier version let a drinking-water question also pull the water-supply
# datasheets, on the reasoning that for a waterworks manufacturer they are the
# same job. It gave breadth but put products into the context that the model then
# listed under a "documented for drinking water" heading although their own
# datasheets never say so — and for a valve, suitability and potable-water
# approval are different claims. Three attempts at wording the prompt around it
# did not hold, so the borrowing was removed instead: with the applications now
# unified across the language editions of a document, an exact match already
# yields eight datasheets for drinking water.
_APPLICATION_TERMS: dict[tuple[str, ...], tuple[str, ...]] = {
    ("irrigation", "irrigate", "sprinkler", "farming", "agricultur"): ("irrigation",),
    ("sewage", "waste water", "wastewater", "sewer"): ("sewage",),
    ("drinking water", "potable", "tap water"): ("drinking water",),
    ("sea water", "seawater", "desalination", "marine"): ("sea water",),
    ("fire fighting", "firefighting", "hydrant", "fire protection"): ("fire fighting",),
    ("pumping station", "pump station"): ("pumping station",),
    # "industrial" alone missed "industry", the commonest phrasing, and the
    # question about industry returned no product at all.
    ("industr", "process plant", "refiner", "petrochemical", "manufacturing"):
        ("industrial",),
    ("water supply", "distribution network", "water main", "aqueduct", "waterworks"):
        ("water supply network",),
    ("mining", "mine ", "quarry"): ("mining",),
    ("deep well", "borehole"): ("deep well",),
    # Non-English wordings, for when translate_to_english fails quietly.
    ("dissalazione", "desalinizzazione", "dessalement", "desalación", "desalacion"):
        ("sea water",),
    ("miniera", "minerario", "minerarios"): ("mining",),
}


def find_application_sources(query: str) -> list[str]:
    """
    Return datasheets documented for the application the question names.

    Application questions ("what do you recommend for irrigation?") cannot be
    served by passage similarity alone: the answer is a *set of products*, and
    the two best-matching chunks come from one or two of them. Pulling the
    application's datasheets in as candidates gives the reranker a spread of
    products to choose between.

    *query* should be the English rendering of the question, since the registry
    was built from the English datasheets.
    """
    registry = _load_registry()
    by_application: dict[str, list[str]] = registry.get("applications", {})
    if not by_application:
        return []

    lowered = query.lower()
    matched: set[str] = set()
    for terms, keys in _APPLICATION_TERMS.items():
        if any(term in lowered for term in terms):
            for key in keys:
                matched.update(by_application.get(key, []))

    priority = set(registry.get("priority_docs", []))
    preferred = sorted(f for f in matched if f in priority)
    rest = sorted(f for f in matched if f not in priority)
    return (preferred + rest)[:MAX_APPLICATION_FILES]


def find_exact_model_source(query: str) -> Optional[str]:
    """
    Return the datasheet whose own model code the query names, if any.

    The keys in `models` are prefixes shared across a family — 'fox 3 f' resolves
    to all nine FOX 3F documents so that a range question reaches them. That left
    no way to tell that FOX_3F.pdf *is* the FOX 3F while the others are variants
    of it, and a question about the base model was answered from a variant: the
    FOX 3F came back at 64 bar, the rating of the carbon-steel FOX 3F-HP, while
    the base valve is ductile iron PN 40.

    `canonical` maps each document's complete code to its file, so the most
    specific code fully named in the question wins: "pressure of the FOX 3F"
    resolves to FOX_3F.pdf, "pressure of the FOX 3F HP" to FOX_3F_HP.pdf.
    """
    registry = _load_registry()
    canonical: dict[str, str] = registry.get("canonical", {})
    if not canonical:
        return None

    sequence = _fuzzy_align(normalize_sequence(query))
    best_key = ""
    for key in canonical:
        key_tokens = key.split()
        if len(key_tokens) >= 2 and _names_model(sequence, key_tokens):
            if len(key_tokens) > len(best_key.split()) if best_key else True:
                best_key = key
    return canonical.get(best_key) if best_key else None


def find_family(query: str) -> Optional[str]:
    """
    The product family the query names, if any — misspellings included.

    Some families publish dimensions once per series in the general catalogue
    only: the ITALICA datasheets carry no dimension table at all, the catalogue
    page "Italica 300 - Dimensioni e pesi" does. Retrieval uses this to fetch
    the family's catalogue pages, which nothing else links to the model name.
    """
    families = _load_registry().get("families", {})
    for token in _fuzzy_align(normalize_sequence(query)):
        if token in families:
            return token
    return None


def find_series_documents(query: str) -> list[str]:
    """
    Return the range-level documents that cover the model the query names.

    Individual XLC datasheets carry no dimensions: not one of XLC_310.pdf,
    XLC_330.pdf and their siblings has a weight table. Sizes and weights are
    published once per range in the XLC engineering document — the XLC 400
    (full bore) and XLC 300 (reduced bore) tables — and a model like the
    XLC 330/430 takes the 300-series figures for its 330 and the 400-series
    figures for its 430. Asked what an XLC 330/430 weighs, the bot read only
    that model's own datasheet and answered that the weight was not documented.
    """
    registry = _load_registry()
    priority: list[str] = registry.get("priority_docs", [])
    if not priority:
        return []

    sequence = _fuzzy_align(normalize_sequence(query))
    families = registry.get("families", {})

    for index, token in enumerate(sequence):
        if token not in families:
            continue
        # The family is named, and the range documents are its priority set.
        covering = [f for f in priority if token in normalize_tokens(f)]
        if covering:
            return covering
    return []


def sources_mentioned(text: str) -> set[str]:
    """
    Return every datasheet whose model code appears in *text*.

    Used to work out which products an answer already covered, so a follow-up
    like "e basta?" can look past them. Unlike find_model_sources this does not
    keep only the most specific match: the point here is completeness, since a
    single answer routinely names four or five products.
    """
    registry = _load_registry()
    sequence = normalize_sequence(text)
    if not sequence:
        return set()

    found: set[str] = set()
    for key, files in registry.get("models", {}).items():
        if _names_model(sequence, key.split()):
            found.update(files)
    return found


def is_catalogue(source_file: str) -> bool:
    """
    True when *source_file* is a general catalogue, not a product datasheet.

    The context labels every other datasheet as "DIFFERENT PRODUCT — never take
    its figures" when the named model's own sheet is present. Applied to the
    catalogue, that instruction forbade the only table in the corpus holding the
    ITALICA dimensions — the family publishes them in the catalogue alone — and
    the bot refused figures it was looking at.
    """
    if not source_file:
        return False
    catalogues = _load_registry().get("catalogues", [])
    if source_file in catalogues:
        return True
    return "catalog" in source_file.lower() or "catalogo" in source_file.lower()


def applications_for(source_file: str) -> list[str]:
    """
    Return the applications a datasheet documents.

    Surfaced in the prompt context because a retrieved chunk often covers
    materials or the operating principle and never repeats what the valve is
    for — so the model saw five products documented for irrigation and named
    only the one whose chunk happened to contain the word.
    """
    if not source_file:
        return []
    registry = _load_registry()
    return sorted(
        name
        for name, files in registry.get("applications", {}).items()
        if source_file in files
    )


def _cap(files: set[str], priority: set[str]) -> list[str]:
    """Trim to MAX_FILES_PER_QUERY, keeping priority documents first."""
    preferred = sorted(f for f in files if f in priority)
    rest = sorted(f for f in files if f not in priority)
    return (preferred + rest)[:MAX_FILES_PER_QUERY]
